image: node:10

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - npm run test

pages:
  stage: deploy
  script:
    - npm run build -- --env.basename=/react-test-task
  artifacts:
    paths:
      - public
  only:
    - master
